    postgresql:
        image: postgres:9.3
        hostname: "${PROJECT_NAME}_db"
        container_name: "${PROJECT_NAME}_db"
        volumes_from:
            - data
        environment:
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_DB: "${DB_NAME}"
    data:
        image: postgres:9.3
        hostname: "${PROJECT_NAME}_postgres_data"
        container_name: "${PROJECT_NAME}_postgres_data"
        volumes:
            - /var/lib/postgresql/data
        command: "true"
